site_name: 'Siva CheatSheets'
site_description: 'My Quick Reference Docs'
site_author: 'K Siva Prasad Reddy'
site_url: 'https://sivaprasadreddy.github.io/cheatsheets/'

# Repository
repo_name: 'sivaprasadreddy/cheatsheets'
repo_url: 'https://github.com/sivaprasadreddy/cheatsheets'

# Copyright
copyright: 'Copyright &copy; 2020 - 2021 K Siva Prasad Reddy'

theme:
  name: material
nav:
    - Home: index.md
    - Learning: learning.md
    - Java:
        - Ecosystem: java/ecosystem.md
        - Maven: java/maven.md
        - Gradle: java/gradle.md
    - Kotlin:
        - Introduction: kotlin/introduction.md
    - SpringBoot:
        - Introduction: springboot/introduction.md
    - Python:
        - Introduction: python/introduction.md
        - Installation: python/installation.md
    - DevOps:
        - Tools: devops/devops.md
        - Linux: devops/linux.md
        - Docker: devops/docker.md
        - Ansible: devops/ansible.md


# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/sivaprasadreddy'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/sivalabs'
    - icon: fontawesome/brands/linkedin
      link: 'https://linkedin.com/in/siva-prasad-reddy-k-3a909172'

# Extensions
markdown_extensions:
  - codehilite
